name: Feature Request
description: Suggest a new feature for RepoAgents
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thank you for suggesting a new feature! This helps improve RepoAgents for everyone.
        
        **Note**: This issue may be processed by AI agents. Please be clear and specific.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a developer using RepoAgents, I want to...
        This would help me because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this problem solved?
      placeholder: |
        The feature should...
        It would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        I also considered...
        But this approach is better because...
    validations:
      required: false

  - type: dropdown
    id: agent
    attributes:
      label: Relevant Agent(s)
      description: Which agent(s) would this feature relate to?
      multiple: true
      options:
        - All Agents (AGENTS.md)
        - GitHub Copilot
        - Google Gemini CLI
        - Anthropic Claude
        - OpenAI Codex
        - OpenCode
        - Google Jules
        - Factory AI
        - Other
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - Simple (few hours)
        - Medium (1-2 days)
        - Complex (3-5 days)
        - Very Complex (1+ weeks)
        - Unknown
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical details, constraints, or suggestions?
      placeholder: |
        This might require changes to...
        We should consider...
    validations:
      required: false

  - type: checkboxes
    id: files
    attributes:
      label: Potentially Affected Files
      description: Which parts of the project might this feature affect?
      options:
        - label: AGENTS.md (main agent instructions)
        - label: Agent configurations (agents/*)
        - label: GitHub workflows (.github/workflows/*)
        - label: Documentation (docs/*)
        - label: Examples (examples/*)
        - label: Tests
        - label: Other (specify in Technical Notes)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples?
      placeholder: |
        Screenshots, mockups, or links to similar features...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to work on this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I would like an AI agent to implement this
        - label: I'm open to either approach
